create table if not exists public.catchmind_drawings (
  id bigint generated by default as identity primary key,
  match_id text not null check (char_length(match_id) between 1 and 80),
  round_index integer not null check (round_index between 0 and 39),
  drawer text not null check (char_length(drawer) between 1 and 40),
  word text not null check (char_length(word) between 1 and 10),
  image_path text not null unique,
  mime_type text not null check (mime_type in ('image/webp', 'image/png')),
  byte_size integer not null check (byte_size between 1 and 307200),
  saved_by text not null check (char_length(saved_by) between 1 and 40),
  created_at timestamptz not null default now(),
  unique (match_id, round_index)
);

create table if not exists public.catchmind_favorites (
  nickname text not null,
  drawing_id bigint not null references public.catchmind_drawings(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (nickname, drawing_id)
);

create index if not exists catchmind_drawings_created_at_idx
  on public.catchmind_drawings (created_at desc, id desc);

create index if not exists catchmind_favorites_drawing_idx
  on public.catchmind_favorites (drawing_id);

create or replace function public.enforce_catchmind_favorite_limit()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  perform pg_advisory_xact_lock(hashtext(new.nickname));
  if (select count(*) from public.catchmind_favorites where nickname = new.nickname) >= 20 then
    raise exception using
      errcode = 'P0001',
      message = 'catchmind_favorite_limit';
  end if;
  return new;
end;
$$;

drop trigger if exists catchmind_favorite_limit on public.catchmind_favorites;
create trigger catchmind_favorite_limit
before insert on public.catchmind_favorites
for each row execute function public.enforce_catchmind_favorite_limit();

alter table public.catchmind_drawings enable row level security;
alter table public.catchmind_favorites enable row level security;

create or replace function public.catchmind_gallery_prune_candidates(max_rows integer default 200)
returns table (id bigint, image_path text)
language sql
security definer
set search_path = public
as $$
  with recent as (
    select d.id
    from public.catchmind_drawings d
    order by d.created_at desc, d.id desc
    limit 1000
  )
  select d.id, d.image_path
  from public.catchmind_drawings d
  where not exists (select 1 from recent r where r.id = d.id)
    and not exists (
      select 1
      from public.catchmind_favorites f
      where f.drawing_id = d.id
    )
  order by d.created_at asc, d.id asc
  limit greatest(1, least(coalesce(max_rows, 200), 500));
$$;

revoke all on public.catchmind_drawings from anon, authenticated;
revoke all on public.catchmind_favorites from anon, authenticated;
revoke all on function public.catchmind_gallery_prune_candidates(integer) from public, anon, authenticated;
grant all on public.catchmind_drawings to service_role;
grant all on public.catchmind_favorites to service_role;
grant usage, select on sequence public.catchmind_drawings_id_seq to service_role;
grant execute on function public.catchmind_gallery_prune_candidates(integer) to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'catchmind-gallery',
  'catchmind-gallery',
  true,
  307200,
  array['image/webp', 'image/png']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- The bucket is public for image reads only. Browser writes stay closed; the
-- catchmind-gallery Edge Function performs authenticated writes with service_role.
