create table if not exists public.catchmind_profiles (
  nickname text primary key check (char_length(nickname) between 1 and 40),
  total_xp bigint not null default 0 check (total_xp between 0 and 883080),
  curve_version smallint not null default 1 check (curve_version between 1 and 99),
  equipped_board_frame text,
  equipped_nameplate text,
  equipped_stickers text[] not null default '{}'::text[]
    check (cardinality(equipped_stickers) <= 4),
  equipped_text_emotes text[] not null default '{}'::text[]
    check (cardinality(equipped_text_emotes) <= 12),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.catchmind_xp_events (
  id bigint generated by default as identity primary key,
  match_id text not null check (
    char_length(match_id) between 1 and 80
    and match_id ~ '^[A-Za-z0-9_-]+$'
  ),
  nickname text not null check (char_length(nickname) between 1 and 40),
  xp integer not null check (xp between 0 and 100),
  applied_xp integer not null check (applied_xp between 0 and xp),
  breakdown jsonb not null default '{}'::jsonb
    check (jsonb_typeof(breakdown) = 'object'),
  context jsonb not null default '{}'::jsonb
    check (jsonb_typeof(context) = 'object'),
  curve_version smallint not null default 1 check (curve_version between 1 and 99),
  created_at timestamptz not null default now(),
  unique (match_id, nickname)
);

create table if not exists public.catchmind_mvp_votes (
  match_id text not null check (
    char_length(match_id) between 1 and 80
    and match_id ~ '^[A-Za-z0-9_-]+$'
  ),
  voter_nickname text not null references public.catchmind_profiles(nickname)
    on update cascade on delete cascade,
  nominee_nickname text not null references public.catchmind_profiles(nickname)
    on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  primary key (match_id, voter_nickname),
  check (voter_nickname <> nominee_nickname)
);

create table if not exists public.catchmind_mvp_results (
  match_id text primary key check (
    char_length(match_id) between 1 and 80
    and match_id ~ '^[A-Za-z0-9_-]+$'
  ),
  winner_nickname text not null references public.catchmind_profiles(nickname)
    on update cascade on delete cascade,
  vote_count integer not null check (vote_count between 1 and 8),
  bonus_xp integer not null default 15 check (bonus_xp = 15),
  applied_xp integer not null check (applied_xp between 0 and bonus_xp),
  finalized_at timestamptz not null default now()
);

create table if not exists public.catchmind_reward_catalog (
  reward_id text primary key check (
    char_length(reward_id) between 1 and 80
    and reward_id ~ '^[a-z0-9-]+$'
  ),
  unlock_level integer not null check (unlock_level between 2 and 100),
  kind text not null check (
    kind in ('board_frame', 'sticker', 'text_emote', 'nameplate', 'bundle')
  ),
  name text not null check (char_length(name) between 1 and 80),
  asset_key text check (asset_key is null or char_length(asset_key) between 1 and 160),
  config jsonb not null default '{}'::jsonb
    check (jsonb_typeof(config) = 'object'),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.catchmind_unlocks (
  nickname text not null check (char_length(nickname) between 1 and 40),
  reward_id text not null references public.catchmind_reward_catalog(reward_id)
    on update cascade on delete cascade,
  unlocked_at timestamptz not null default now(),
  primary key (nickname, reward_id)
);

create index if not exists catchmind_xp_events_nickname_created_idx
  on public.catchmind_xp_events (nickname, created_at desc);

create index if not exists catchmind_mvp_votes_match_nominee_idx
  on public.catchmind_mvp_votes (match_id, nominee_nickname);

create index if not exists catchmind_reward_catalog_level_idx
  on public.catchmind_reward_catalog (unlock_level, active);

create index if not exists catchmind_unlocks_nickname_idx
  on public.catchmind_unlocks (nickname, unlocked_at desc);

create or replace function public.catchmind_level_for_xp(p_total_xp bigint)
returns integer
language plpgsql
immutable
strict
set search_path = public
as $$
declare
  v_total bigint := greatest(0, least(p_total_xp, 883080));
  v_start bigint := 0;
  v_needed bigint;
  v_level integer;
begin
  for v_level in 1..99 loop
    v_needed := (round((60 + 18 * v_level + 2.4 * v_level * v_level) / 5.0) * 5)::bigint;
    if v_total < v_start + v_needed then
      return v_level;
    end if;
    v_start := v_start + v_needed;
  end loop;
  return 100;
end;
$$;

create or replace function public.award_catchmind_xp(
  p_match_id text,
  p_nickname text,
  p_xp integer,
  p_breakdown jsonb default '{}'::jsonb,
  p_context jsonb default '{}'::jsonb,
  p_curve_version smallint default 1
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before bigint;
  v_after bigint;
  v_applied integer;
  v_existing integer;
  v_level_before integer;
  v_level_after integer;
begin
  if p_match_id is null
    or p_match_id !~ '^[A-Za-z0-9_-]{1,80}$'
    or p_nickname is null
    or char_length(p_nickname) not between 1 and 40
    or p_xp is null
    or p_xp not between 0 and 100
    or p_curve_version is null
    or p_curve_version not between 1 and 99
    or jsonb_typeof(coalesce(p_breakdown, '{}'::jsonb)) <> 'object'
    or jsonb_typeof(coalesce(p_context, '{}'::jsonb)) <> 'object'
  then
    raise exception using errcode = '22023', message = 'invalid_catchmind_xp_award';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('catchmind-xp:' || p_nickname, 0));

  insert into public.catchmind_profiles (nickname, curve_version)
  values (p_nickname, p_curve_version)
  on conflict (nickname) do nothing;

  select total_xp
  into v_before
  from public.catchmind_profiles
  where nickname = p_nickname
  for update;

  select applied_xp
  into v_existing
  from public.catchmind_xp_events
  where match_id = p_match_id and nickname = p_nickname;

  if found then
    return jsonb_build_object(
      'ok', true,
      'duplicate', true,
      'requestedXp', p_xp,
      'originalAppliedXp', v_existing,
      'appliedXp', 0,
      'beforeXp', v_before,
      'afterXp', v_before,
      'levelBefore', public.catchmind_level_for_xp(v_before),
      'levelAfter', public.catchmind_level_for_xp(v_before)
    );
  end if;

  v_after := least(883080, v_before + p_xp);
  v_applied := (v_after - v_before)::integer;
  v_level_before := public.catchmind_level_for_xp(v_before);
  v_level_after := public.catchmind_level_for_xp(v_after);

  insert into public.catchmind_xp_events (
    match_id,
    nickname,
    xp,
    applied_xp,
    breakdown,
    context,
    curve_version
  )
  values (
    p_match_id,
    p_nickname,
    p_xp,
    v_applied,
    coalesce(p_breakdown, '{}'::jsonb),
    coalesce(p_context, '{}'::jsonb),
    p_curve_version
  );

  update public.catchmind_profiles
  set total_xp = v_after,
      curve_version = p_curve_version,
      updated_at = now()
  where nickname = p_nickname;

  insert into public.catchmind_unlocks (nickname, reward_id)
  select p_nickname, reward.reward_id
  from public.catchmind_reward_catalog reward
  where reward.active
    and reward.unlock_level <= v_level_after
  on conflict (nickname, reward_id) do nothing;

  return jsonb_build_object(
    'ok', true,
    'duplicate', false,
    'requestedXp', p_xp,
    'appliedXp', v_applied,
    'beforeXp', v_before,
    'afterXp', v_after,
    'levelBefore', v_level_before,
    'levelAfter', v_level_after
  );
end;
$$;

create or replace function public.cast_catchmind_mvp_vote(
  p_match_id text,
  p_voter text,
  p_nominee text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_existing text;
  v_vote_count integer;
begin
  if p_match_id is null
    or p_match_id !~ '^[A-Za-z0-9_-]{1,80}$'
    or p_voter is null
    or char_length(p_voter) not between 1 and 40
    or p_nominee is null
    or char_length(p_nominee) not between 1 and 40
    or p_voter = p_nominee
  then
    raise exception using errcode = '22023', message = 'invalid_catchmind_mvp_vote';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('catchmind-mvp:' || p_match_id, 0));

  if exists (
    select 1 from public.catchmind_mvp_results where match_id = p_match_id
  ) then
    return jsonb_build_object('ok', false, 'reason', 'closed');
  end if;

  if not exists (
    select 1
    from public.catchmind_xp_events
    where match_id = p_match_id and nickname = p_voter
  ) or not exists (
    select 1
    from public.catchmind_xp_events
    where match_id = p_match_id and nickname = p_nominee
  ) then
    raise exception using errcode = '22023', message = 'mvp_vote_requires_match_participants';
  end if;

  select nominee_nickname
  into v_existing
  from public.catchmind_mvp_votes
  where match_id = p_match_id and voter_nickname = p_voter;

  if found then
    return jsonb_build_object(
      'ok', true,
      'duplicate', true,
      'nominee', v_existing
    );
  end if;

  insert into public.catchmind_mvp_votes (
    match_id,
    voter_nickname,
    nominee_nickname
  )
  values (p_match_id, p_voter, p_nominee);

  select count(*)::integer
  into v_vote_count
  from public.catchmind_mvp_votes
  where match_id = p_match_id;

  return jsonb_build_object(
    'ok', true,
    'duplicate', false,
    'nominee', p_nominee,
    'voteCount', v_vote_count
  );
end;
$$;

create or replace function public.finalize_catchmind_mvp(
  p_match_id text,
  p_requester text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_participants integer;
  v_expected integer;
  v_vote_count integer;
  v_started_at timestamptz;
  v_deadline timestamptz;
  v_winner text;
  v_winner_votes integer;
  v_before bigint;
  v_after bigint;
  v_applied integer;
  v_existing_bonus integer;
  v_existing_applied integer;
begin
  if p_match_id is null
    or p_match_id !~ '^[A-Za-z0-9_-]{1,80}$'
    or p_requester is null
    or char_length(p_requester) not between 1 and 40
  then
    raise exception using errcode = '22023', message = 'invalid_catchmind_mvp_result';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('catchmind-mvp:' || p_match_id, 0));

  if not exists (
    select 1
    from public.catchmind_xp_events
    where match_id = p_match_id and nickname = p_requester
  ) then
    raise exception using errcode = '22023', message = 'mvp_result_requires_match_participant';
  end if;

  select winner_nickname, vote_count, bonus_xp, applied_xp
  into v_winner, v_winner_votes, v_existing_bonus, v_existing_applied
  from public.catchmind_mvp_results
  where match_id = p_match_id;

  if found then
    return jsonb_build_object(
      'ok', true,
      'status', 'finalized',
      'winner', v_winner,
      'votes', v_winner_votes,
      'bonusXp', v_existing_bonus,
      'appliedXp', v_existing_applied
    );
  end if;

  select
    count(*)::integer,
    min(created_at),
    least(
      8,
      greatest(
        count(*)::integer,
        coalesce(max(
          case
            when context->>'humanPlayers' ~ '^[0-9]+$'
              then (context->>'humanPlayers')::integer
            else null
          end
        ), count(*)::integer)
      )
    )
  into v_participants, v_started_at, v_expected
  from public.catchmind_xp_events
  where match_id = p_match_id;

  if v_participants < 2 or v_started_at is null then
    raise exception using errcode = '22023', message = 'mvp_result_requires_two_participants';
  end if;

  v_deadline := v_started_at + interval '15 seconds';

  select count(*)::integer
  into v_vote_count
  from public.catchmind_mvp_votes
  where match_id = p_match_id;

  if v_vote_count < v_expected and clock_timestamp() < v_deadline then
    return jsonb_build_object(
      'ok', true,
      'status', 'pending',
      'votes', v_vote_count,
      'expected', v_expected,
      'remainingMs', greatest(
        0,
        floor(extract(epoch from (v_deadline - clock_timestamp())) * 1000)::integer
      )
    );
  end if;

  if v_vote_count = 0 then
    return jsonb_build_object(
      'ok', true,
      'status', 'no_votes',
      'bonusXp', 0,
      'appliedXp', 0
    );
  end if;

  select nominee_nickname, count(*)::integer
  into v_winner, v_winner_votes
  from public.catchmind_mvp_votes
  where match_id = p_match_id
  group by nominee_nickname
  order by count(*) desc, md5(p_match_id || ':' || nominee_nickname), nominee_nickname
  limit 1;

  select total_xp
  into v_before
  from public.catchmind_profiles
  where nickname = v_winner
  for update;

  v_after := least(883080, v_before + 15);
  v_applied := (v_after - v_before)::integer;

  update public.catchmind_profiles
  set total_xp = v_after,
      updated_at = now()
  where nickname = v_winner;

  update public.catchmind_xp_events
  set xp = xp + 15,
      applied_xp = applied_xp + v_applied,
      breakdown = jsonb_set(
        coalesce(breakdown, '{}'::jsonb),
        '{xp,mvp}',
        to_jsonb(15),
        true
      )
  where match_id = p_match_id and nickname = v_winner;

  insert into public.catchmind_mvp_results (
    match_id,
    winner_nickname,
    vote_count,
    bonus_xp,
    applied_xp
  )
  values (p_match_id, v_winner, v_winner_votes, 15, v_applied);

  insert into public.catchmind_unlocks (nickname, reward_id)
  select v_winner, reward.reward_id
  from public.catchmind_reward_catalog reward
  where reward.active
    and reward.unlock_level <= public.catchmind_level_for_xp(v_after)
  on conflict (nickname, reward_id) do nothing;

  return jsonb_build_object(
    'ok', true,
    'status', 'finalized',
    'winner', v_winner,
    'votes', v_winner_votes,
    'bonusXp', 15,
    'appliedXp', v_applied
  );
end;
$$;

insert into public.catchmind_reward_catalog (
  reward_id,
  unlock_level,
  kind,
  name,
  asset_key
)
values
  ('sticker-pencil', 2, 'sticker', '연필 반짝 스티커', 'sticker/pencil'),
  ('emote-nice-drawing', 5, 'text_emote', '그림 좋다! 이모티콘', 'emote/nice-drawing'),
  ('nameplate-sprout', 10, 'nameplate', '새싹 닉네임 박스', 'nameplate/sprout'),
  ('sticker-paint-drop', 15, 'sticker', '물감 방울 스티커', 'sticker/paint-drop'),
  ('frame-blue-pencil', 20, 'board_frame', '파란 연필 그림판 테두리', 'frame/blue-pencil'),
  ('nameplate-color', 25, 'nameplate', '컬러 닉네임 박스', 'nameplate/color'),
  ('emote-got-it', 30, 'text_emote', '알겠다! 이모티콘', 'emote/got-it'),
  ('frame-color-pencil', 40, 'board_frame', '색연필 그림판 테두리', 'frame/color-pencil'),
  ('nameplate-artist', 50, 'nameplate', '작가 닉네임 박스', 'nameplate/artist'),
  ('sticker-crown-brush', 60, 'sticker', '왕관 붓 스티커', 'sticker/crown-brush'),
  ('nameplate-master', 75, 'nameplate', '명장 닉네임 박스', 'nameplate/master'),
  ('frame-master', 80, 'board_frame', '명장 그림판 테두리', 'frame/master'),
  ('nameplate-grand', 90, 'nameplate', '거장 닉네임 박스', 'nameplate/grand'),
  ('sticker-firework', 95, 'sticker', '불꽃 스티커', 'sticker/firework'),
  ('legend-bundle', 100, 'bundle', '레전드 전용 꾸미기 세트', 'bundle/legend')
on conflict (reward_id) do update set
  unlock_level = excluded.unlock_level,
  kind = excluded.kind,
  name = excluded.name,
  asset_key = excluded.asset_key;

alter table public.catchmind_profiles enable row level security;
alter table public.catchmind_xp_events enable row level security;
alter table public.catchmind_mvp_votes enable row level security;
alter table public.catchmind_mvp_results enable row level security;
alter table public.catchmind_reward_catalog enable row level security;
alter table public.catchmind_unlocks enable row level security;

revoke all on public.catchmind_profiles from anon, authenticated;
revoke all on public.catchmind_xp_events from anon, authenticated;
revoke all on public.catchmind_mvp_votes from anon, authenticated;
revoke all on public.catchmind_mvp_results from anon, authenticated;
revoke all on public.catchmind_reward_catalog from anon, authenticated;
revoke all on public.catchmind_unlocks from anon, authenticated;
revoke all on function public.catchmind_level_for_xp(bigint) from public, anon, authenticated;
revoke all on function public.award_catchmind_xp(text, text, integer, jsonb, jsonb, smallint)
  from public, anon, authenticated;
revoke all on function public.cast_catchmind_mvp_vote(text, text, text)
  from public, anon, authenticated;
revoke all on function public.finalize_catchmind_mvp(text, text)
  from public, anon, authenticated;

grant all on public.catchmind_profiles to service_role;
grant all on public.catchmind_xp_events to service_role;
grant all on public.catchmind_mvp_votes to service_role;
grant all on public.catchmind_mvp_results to service_role;
grant all on public.catchmind_reward_catalog to service_role;
grant all on public.catchmind_unlocks to service_role;
grant usage, select on sequence public.catchmind_xp_events_id_seq to service_role;
grant execute on function public.catchmind_level_for_xp(bigint) to service_role;
grant execute on function public.award_catchmind_xp(text, text, integer, jsonb, jsonb, smallint)
  to service_role;
grant execute on function public.cast_catchmind_mvp_vote(text, text, text)
  to service_role;
grant execute on function public.finalize_catchmind_mvp(text, text)
  to service_role;
