create table if not exists public.relay_albums (
  id bigint generated by default as identity primary key,
  match_id text not null check (char_length(match_id) between 1 and 80),
  origin text not null check (char_length(origin) between 1 and 40),
  start_text text not null check (char_length(start_text) between 1 and 40),
  player_count integer not null check (player_count between 3 and 12),
  entry_count integer not null check (entry_count between 3 and 12),
  cover_path text,
  saved_by text not null check (char_length(saved_by) between 1 and 40),
  created_at timestamptz not null default now(),
  unique (match_id, origin)
);

create table if not exists public.relay_album_entries (
  album_id bigint not null references public.relay_albums(id) on delete cascade,
  step_index integer not null check (step_index between 0 and 11),
  kind text not null check (kind in ('prompt', 'drawing', 'caption')),
  author text not null check (char_length(author) between 1 and 40),
  body_text text check (body_text is null or char_length(body_text) between 1 and 40),
  image_path text unique,
  mime_type text check (mime_type is null or mime_type = 'image/webp'),
  byte_size integer check (byte_size is null or byte_size between 1 and 153600),
  primary key (album_id, step_index),
  check (
    (kind = 'drawing' and body_text is null and image_path is not null and mime_type is not null and byte_size is not null)
    or (kind <> 'drawing' and body_text is not null and image_path is null and mime_type is null and byte_size is null)
  )
);

create index if not exists relay_albums_created_at_idx
  on public.relay_albums (created_at desc, id desc);

create index if not exists relay_album_entries_album_idx
  on public.relay_album_entries (album_id, step_index);

alter table public.relay_albums enable row level security;
alter table public.relay_album_entries enable row level security;

create or replace function public.relay_gallery_prune_candidates(max_albums integer default 20)
returns table (id bigint)
language sql
security definer
set search_path = public
as $$
  with recent as (
    select a.id
    from public.relay_albums a
    order by a.created_at desc, a.id desc
    limit 100
  )
  select a.id
  from public.relay_albums a
  where not exists (select 1 from recent r where r.id = a.id)
  order by a.created_at asc, a.id asc
  limit greatest(1, least(coalesce(max_albums, 20), 100));
$$;

revoke all on public.relay_albums from anon, authenticated;
revoke all on public.relay_album_entries from anon, authenticated;
revoke all on function public.relay_gallery_prune_candidates(integer) from public, anon, authenticated;
grant all on public.relay_albums to service_role;
grant all on public.relay_album_entries to service_role;
grant usage, select on sequence public.relay_albums_id_seq to service_role;
grant execute on function public.relay_gallery_prune_candidates(integer) to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'relay-gallery',
  'relay-gallery',
  true,
  153600,
  array['image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Public image reads are allowed through the bucket URL. Browser writes remain
-- closed; the relay-gallery Edge Function owns validated writes and pruning.
